### ISSUE TITLE
Why record type fields start lowercase?

### ISSUE THREAD

**Issue by burak-yildirim** [Zaid-Ajaj/Fable.SimpleHttp#40]
In **src/Types.fs** some record types' fields, like ```HttpResponse``` and ```HttpRequest``` fields, start with lowercase letter. But in F# by convention record field names should start with Uppercase letter. Why are they lowercase?

**Comment by Zaid-Ajaj** [comment]
Hi there @burak-yildirim, the reason is just a personal preference because I feel like uppercased fields _scream_ into the screen when I read the code, so lowercased field names are easier on the eye :) also since this is used XMLHttpRequest under the hood, I try to keep it close to the field names of the XHR (which are lowercased fields)

**Comment by burak-yildirim** [comment]
Thanks for fast reply and explanation @Zaid-Ajaj !
