### ISSUE TITLE
How to use apis for Fable

### ISSUE THREAD

**Issue by albertwoo** [Zaid-Ajaj/Fable.SimpleHttp#7]
I am using Fable.SimpleHttp 2.1.0 with my fable project, but I could not find `Http.request`. How I can use them?
![SimpleHttp issue1](https://user-images.githubusercontent.com/8017681/60635063-daa8be00-9e43-11e9-8a6b-815edafdd91f.png)

**Comment by stroborobo** [comment]
This is because Intellisense uses the dotnet compiled version, not what Fable would output. There are simply no implementations for all functions in dotnet, most are just available to Fable. So you can safely use the Http.request function in a Fable context.

@Zaid-Ajaj Would it be ok to maybe add all functions with just `failwith "not implemented"`, so the tools work?

**Comment by Zaid-Ajaj** [comment]
Hello @albertwoo, sorry for the late answer, this issue slipped by without me noticing :/ 

The issue is as @stroborobo noted you can still just right the functions and they would work, the intellisense of Visual Studio is acting weird and not picking up the FABLE_COMPILER specific compilation flag during development time

> @Zaid-Ajaj Would it be ok to maybe add all functions with just failwith "not implemented", so the tools work? 

Sure thing, please go for it 🙏 if you don't have time, I'll try to fix myself these days when time permits
